/*
 * This source file was generated by the Gradle 'init' task
 */
package org.micahgruenwald.mandelbrotmultithread;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
















class AppTest {
  public static void main(String[] args) {
    testSingleMandelbrot();
    // testManager();
  }

  public static void testSingleMandelbrot() {
    BufferedImage image = new BufferedImage(500, 500, BufferedImage.TYPE_INT_RGB);
    MandelbrotThread mandelbrot1 =
        new MandelbrotThread(-1.25, -2.0, 1.25, .5, 0, 0, 500,500, image);
    mandelbrot1.start();

    try {
      mandelbrot1.join();
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    } catch (InterruptedException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }

  public static void testManager(){
    long ti = System.nanoTime();
    BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
    Manager manager = new Manager(2, new RenderArea(-0.75, 0, 2.5,2.5), image);
    manager.run();
    System.out.println("Runtime: " + (System.nanoTime() - ti) * 1e-9);
        try {
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    }
  }
}
