/*
 * This source file was generated by the Gradle 'init' task
 */
package org.micahgruenwald.mandelbrotmultithread;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

class AppTest {
  public static void main(String[] args) {
    // testSingleMandelbrot();
    testManager();
  }

  public static void testSingleMandelbrot() {
    BufferedImage image = new BufferedImage(500, 500, BufferedImage.TYPE_INT_RGB);
    MandelbrotThread mandelbrot1 =
        new MandelbrotThread(-2.0, -1.25, -0.75, 0.0, 0.005, 0.005, 0, 0, image);
    MandelbrotThread mandelbrot2 =
        new MandelbrotThread(-2.0, 0, -0.75, 1.25, 0.005, 0.005, 0, 250, image);
    MandelbrotThread mandelbrot3 =
        new MandelbrotThread(-0.75, -1.25, .5, 0.0, 0.005, 0.005, 250, 0, image);
    MandelbrotThread mandelbrot4 =
        new MandelbrotThread(-0.75, 0.0, 0.5, 1.25, 0.005, 0.005, 250, 250, image);
    mandelbrot1.start();
    mandelbrot2.start();
    mandelbrot3.start();
    mandelbrot4.start();

    try {
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    }
  }

  public static void testManager(){
    long ti = System.nanoTime();
    BufferedImage image = new BufferedImage(158, 79, BufferedImage.TYPE_INT_RGB);
    Manager manager = new Manager(19, new RenderArea(-0.75, 0, 5.0,2.5), image);
    manager.start();

    while (manager.isAlive()) { 
      try{
        Thread.sleep(5);
      }catch(Exception e){}
      try {
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    }
  }
    try {
        manager.join();
        System.out.println("Runtime: " + (System.nanoTime() - ti) * 1e-9);
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    } catch (InterruptedException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    System.out.println("Done!");
  }
}
